### ISSUE TITLE
Dust is not working in node v0.6

### ISSUE THREAD

**Issue by snatesan** [akdubya/dustjs#43]
Hi,

Just wanted to let you know that Dust is not working in the latest version of node. It throws the following exception

Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (/Users/satheesh/NodeTraining/Express/node_modules/dust/lib/server.js:6:8)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/satheesh/NodeTraining/Express/node_modules/dust/lib/dust.js:511:7)
    at Module._compile (module.js:432:26)

Thanks!

**Comment by stanpalatnik** [comment]
Solved here: https://github.com/akdubya/dustjs/pull/39

**Comment by vybs** [comment]
Solved here too : https://github.com/linkedin/dustjs
