### ISSUE TITLE
No such module: evals

### ISSUE THREAD

**Issue by dcsan** [akdubya/dustjs#75]
got the following on trying to use Dust. is there a dependency missing?

env: node 7.9

```
  localDataPath: '/Users/dc/dev/rikai/tutorbot/papp/server/data' } +0ms
/Users/dc/dev/rikai/tutorbot/papp/server/node_modules/dust/lib/server.js:4
    Script = process.binding('evals').Script;
                     ^

Error: No such module: evals
    at Object.<anonymous> (/Users/dc/dev/rikai/tutorbot/papp/server/node_modules/dust/lib/server.js:4:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dc/dev/rikai/tutorbot/papp/server/node_modules/dust/lib/dust.js:511:7)
    at Module._compile (module.js:571:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by LucStr** [comment]
Same here, any fix for this?

Using Node v.8.11.1 on Windows 10

**Comment by LucStr** [comment]
I was able to fix it by using the following fork:

https://github.com/caolan/dustjs
